CREATE TABLE CURSOS (COD_CUR VARCHAR(10) PRIMARY KEY NOT NULL, DESCRIPCION VARCHAR(30), HORAS INT, TUTOR VARCHAR(30));
CREATE TABLE ALUMNOS (COD_ALU VARCHAR(10) PRIMARY KEY NOT NULL, COD_CUR VARCHAR(10) NOT NULL, DNI VARCHAR(10), APELLIDOS VARCHAR(30), NOMBRE VARCHAR(20));
CREATE TABLE NOTAS (COD_CUR VARCHAR(10) NOT NULL, COD_ALU VARCHAR(10) NOT NULL, NOTA1 INT, NOTA2 INT, NOTA3 INT, MEDIA INT, PRIMARY KEY (COD_CUR, COD_ALU));




